name: Funktion vorschlagen
description: Schlagen Sie eine Funktion für dieses Programm vor.
assignees: bennetrr
labels: 'feature'
body:
- type: markdown
  attributes:
    value: |
      Vielen Dank, dass Sie sich die Zeit nehmen, dieses Formular auszufüllen! Bitte beantworten Sie ein paar Fragen, damit wir wissen, was Sie in diesem Programm haben möchten.
      Bitte gucken Sie nach, ob die gewünste Funktion schon in der neusten Version des Programms enthalten ist oder [hier](https://github.com/bennetrr/CovidSimulation/issues?q=is%3Aissue+label%3Afeature) schon vorgeschlagen wurde.
- type: textarea
  id: feature-desc
  attributes:
    label: Beschreiben Sie die Funktion
  validations:
    required: true
- type: textarea
  id: problem-related
  attributes:
    label: Bezieht sich die gewünschte Funktion auf ein Problem?
    description: Beschreiben Sie das Problem. Gehen Sie auch auf Workarounds und andere Lösungen ein, die Sie genutzt haben.
