name: Fehlerbericht
description: Melde uns einen Fehler, um uns dabei zu helfen, die Map fehlerfrei zu machen.
labels: bug
assignees: bennetrr
body:
- type: markdown
  attributes:
    value: |
      Vielen Dank, dass du dir Zeit nimmst, diesen Fehlerbericht auszufüllen! Bitte beantworte ein paar Fragen, damit wir den Fehler besser verstehen.
      Vorher solltest du aber überprüfen, ob du auch die neuste Version der Map und auch Minecraft Java 1.17 oder neuer benutzt.
      Außerdem solltest du [hier](https://github.com/bennetrr/VanillaBedwars/issues?q=is%3Aissue+label%3Abug+) nachschauen, ob nicht schon jemand anderes diesen oder einen ähnlichen Fehler gemeldet hat.
- type: textarea
  id: bug-desc
  attributes:
    label: Fehlerbeschreibung
    description: Beschreibe, wie der Fehler aussieht. Bitte füge auch Fehlermeldungen ein, um uns technische Informationen zu geben, und lade Screenshots vom Fehler und die Log-Dateien von Minecraft und dem Server hier hoch.
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduktionsschritte
    description: |
      Wodurch hast du den Fehler ausgelöst? Bitte teile uns Schritt für Schritt mit, was du gemacht hast, bevor / als der Fehler auftrat.
      Dadurch können wir den Fehler selbst auslösen und ihn mit unseren Tools auseinandernehmen.
    value: |
      1.
      2.
      3.
      ...
- type: markdown
  attributes:
    value: '# Client-Systeminformationen'
- type: dropdown
  id: client-ver
  attributes:
    label: Minecraft-Version
    description: Bitte gebe die von dir verwendete Minecraft-Version an
    options:
      - 1.17.1
      - 1.17
      - 1.17-Snapshot
      - 1.17.1-Snapshot
  validations:
    required: true
- type: dropdown
  id: client-modloader
  attributes:
    label: Modloader
    description: Bitte gebe den von dir verwendeten Modloader an
    options:
      - keinen
      - Forge
      - Fabric
      - andere
  validations:
    required: true
body:
- type: input
  id: client-mods
  attributes:
    label: Mods
    description: Bitte gebe installierte Mods an (wenn du keine installiert hast, einfach leer lassen)
    placeholder: OptiFine, Xaeros Minimap, ...
  validations:
    required: false
- type: markdown
  attributes:
    value: '# Server-Systeminformationen'
- type: markdown
  attributes:
    value: Falls du diese Infos nicht hast, fragen den, der den Server verwaltet
- type: dropdown
  id: server-ver
  attributes:
    label: Minecraft-Version
    description: Bitte gebe die auf dem Server installierte Minecraft-Version an
    options:
      - 1.17.1
      - 1.17
      - 1.17-Snapshot
      - 1.17.1-Snapshot
  validations:
    required: true
- type: dropdown
  id: server-modloader
  attributes:
    label: Modloader
    description: Bitte gebe die auf dem Server installierte Serversoftware an
    options:
      - Vanilla
      - CraftBukkit
      - Spigot
      - Paper
      - Tuinity
      - Purpur
  validations:
    required: true
body:
- type: input
  id: server-mods
  attributes:
    label: Mods
    description: Bitte gebe installierte Mods / Plugins an (wenn du keine installiert hast, einfach leer lassen)
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      Das wars auch schon! Dein Fehlerbericht wird nach dem absenden in kürze von uns bearbeitet.
