name: Funktion vorschlagen
description: Hier kannst du eine Funktion für diese Map vorschlagen
assignees: bennetrr
labels: 'feature'
body:
- type: markdown
  attributes:
    value: |
      Danke, dass du dir die Zeit nimmst, dieses Formular auszufüllen! Bitte beantworte ein paar Fragen, damit wir wissen, was du dir in dieser Map wünscht.
      Überprüfe aber vorher, ob die gewünschte Funktion schon in der neusten Version der Map enthalten ist oder sie [hier](https://github.com/bennetrr/VanillaBedwars/issues?q=is%3Aissue+label%3Afeature) schon vorgeschlagen wurde.
- type: textarea
  id: feature-desc
  attributes:
    label: Beschreibe die Funktion
  validations:
    required: true
- type: textarea
  id: problem-related
  attributes:
    label: Bezieht sich die gewünschte Funktion auf ein Problem?
    description: Beschreibe das Problem. Gehe auch auf Workarounds und andere Lösungen ein, die du genutzt hast.
