name: Build zip package

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Copy files
        run: |
          mkdir -v VanillaBedwars
          cp -vr data VanillaBedwars/data
          cp -vr datapacks VanillaBedwars/datapacks
          cp -vr entities VanillaBedwars/entities
          cp -vr poi VanillaBedwars/poi
          cp -vr region VanillaBedwars/region
          cp -vr level.dat VanillaBedwars/level.dat
          cp -vr session.lock VanillaBedwars/session.lock
          cp -vr uid.dat VanillaBedwars/uid.dat
      
      - name: Build
        run: zip -vr VanillaBedwars.zip VanillaBedwars
        
      - name: Upload to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: VanillaBedwars.zip
          asset_name: VanillaBedwars_${{ github.event.release.tag_name }}.zip
          asset_content_type: binary/octet-stream
